#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
# This script should be run from the project root.
set -e

# Find the project root by looking for the .git directory
PROJECT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || realpath "$(dirname "$0")/..")
cd "$PROJECT_ROOT"

echo "🚀 Starting Devnet deployment process..."

# --- 1. Build and Deploy Anchor programs ---
echo "🛠️  Building and deploying programs to Devnet... (This may take a moment)"

# Capture the output of the deploy command
DEPLOY_OUTPUT=$(cd contracts && anchor deploy --provider.cluster devnet)

echo "$DEPLOY_OUTPUT"
echo "✅ Programs deployed successfully."

# --- 2. Extract Program IDs ---
echo "🔍 Extracting program IDs..."

DONATION_POOL_ID=$(echo "$DEPLOY_OUTPUT" | grep "Deploying program \"donation_pool\"" | sed -n 's/.*Program ID: //p')
NFT_TRACKER_ID=$(echo "$DEPLOY_OUTPUT" | grep "Deploying program \"nft_tracker\"" | sed -n 's/.*Program ID: //p')

if [ -z "$DONATION_POOL_ID" ] || [ -z "$NFT_TRACKER_ID" ]; then
  echo "❌ Error: Could not extract program IDs. Aborting."
  exit 1
fi

echo "   - Donation Pool ID: $DONATION_POOL_ID"
echo "   - NFT Tracker ID:   $NFT_TRACKER_ID"

# --- 4. Write Program IDs to JSON and .env files ---
echo "✍️  Writing program IDs to configuration files..."

# Create a JSON file for easy access
printf '{\n  "donation_pool": "%s",\n  "nft_tracker": "%s"\n}\n' "$DONATION_POOL_ID" "$NFT_TRACKER_ID" > program-ids.json
echo "   - Created contracts/program-ids.json"

# Navigate back to the root
cd ..

# Update .env.example files
sed -i'' -e '/DONATION_POOL_PROGRAM_ID/d' backend/.env.example
sed -i'' -e '/NFT_TRACKER_PROGRAM_ID/d' backend/.env.example
echo -e "\n# Solana Program IDs (auto-generated by deploy script)\nDONATION_POOL_PROGRAM_ID=$DONATION_POOL_ID\nNFT_TRACKER_PROGRAM_ID=$NFT_TRACKER_ID" >> backend/.env.example
echo "   - Updated backend/.env.example"

sed -i'' -e '/VITE_DONATION_POOL_PROGRAM_ID/d' frontend/.env.example
sed -i'' -e '/VITE_NFT_TRACKER_PROGRAM_ID/d' frontend/.env.example
echo -e "\n# Solana Program IDs (auto-generated by deploy script)\nVITE_DONATION_POOL_PROGRAM_ID=$DONATION_POOL_ID\nVITE_NFT_TRACKER_PROGRAM_ID=$NFT_TRACKER_ID" >> frontend/.env.example
echo "   - Updated frontend/.env.example"

echo "🎉 Deployment complete! Run 'bash scripts/setup-dev.sh' to copy new env variables."